pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/runalp97/devopsigy-flaskapp.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t flaskapp:v1 ./docker'
            }
        }

        stage('Push to DockerHub') {
            steps {
                sh 'docker tag flaskapp:v1 yourdockerhub/flaskapp:v1'
                sh 'docker push yourdockerhub/flaskapp:v1'
            }
        }

        stage('Deploy to App EC2') {
            steps {
                sshagent(credentials: ['ssh-key']) {
                    sh '''
          ssh -o StrictHostKeyChecking=no ubuntu@<APP_EC2_IP> "
            docker pull yourdockerhub/flaskapp:v1 &&
            docker stop flaskapp || true &&
            docker rm flaskapp || true &&
            docker run -d --name flaskapp -p 5000:5000 yourdockerhub/flaskapp:v1
          "
          '''
                }
            }
        }

        stage('Notify Slack') {
            steps {
                slackSend(channel: '#deployments', message: '✅ Flask App Deployed Successfully!')
            }
        }
    }
}
