- hosts: app
  become: yes
  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Run Prometheus
      docker_container:
        name: prometheus
        image: prom/prometheus
        state: started
        ports:
          - "9090:9090"

    - name: Run Grafana
      docker_container:
        name: grafana
        image: grafana/grafana
        state: started
        ports:
          - "3000:3000"
