- hosts: jenkins
  become: yes
  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: ['openjdk-11-jdk', 'git', 'docker.io', 'curl']
        state: present

    - name: Add Jenkins repo
      shell: |
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee \
          /usr/share/keyrings/jenkins-keyring.asc > /dev/null
        echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
          https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
          /etc/apt/sources.list.d/jenkins.list > /dev/null

    - name: Install Jenkins
      apt:
        update_cache: yes
        name: jenkins
        state: present

    - name: Start Jenkins
      systemd:
        name: jenkins
        enabled: yes
        state: started

    - name: Start Docker
      systemd:
        name: docker
        enabled: yes
        state: started
